### PR TITLE
Bugfix, in requirements.txt

### PR DESCRIPTION
**Pull request by Abhijeetbyte**
Calling the wrong modules name

tkinter => tk
tempfle => temp

image

### CODE REVIEW

**Comment by mohammadbourbour** [comment]
> Calling the wrong modules name
> 
> tkinter => tk tempfle => temp
> 
> image

Thank you for contribute

**Review by Abhijeetbyte — COMMENTED** [review]
There is no, module called `os` which is installable.

image

<br/>

Why don't you just merge the pull request ?

**Comment by mohammadbourbour** [comment]
> There is no, module called `os` which is installable.
> 
> image
> 
> 
> Why don't you just merge the pull request ?

Because I am new to github, i just found out about merge pull request 
Anyway, I did it now, thank you

**Comment by Abhijeetbyte** [comment]
You're Welcome!

Also, you have issues like this in your other projects too! kindly address it

**Pull request merged**
